In [1]:
import numpy as np
import pandas as pd 
import cv2
import glob
import os

In [16]:
train_path = '/Kodlar/MachineLearning/Proje2/train' 
test_path = '/Kodlar/MachineLearning/Proje2/test/'

In [17]:
images = []
train_df = pd.DataFrame()
test_df = pd.DataFrame()
train_df['images'] = os.listdir(train_path+'/cat') + os.listdir(train_path+'/dog') + os.listdir(train_path+'/wild') 
test_df['images'] = os.listdir(test_path+'/cat') + os.listdir(test_path+'/dog') + os.listdir(test_path+'/wild')

classes = []
paths = []
for image in train_df['images']:
    class_ = image.split('_')[1]
    classes.append(class_)
    paths.append(train_path+'/'+class_+'/'+image)

train_df['classes'] = classes
train_df['path'] = paths

# ------------------------------------------------------------------

classes = []
paths = []
for image in test_df['images']:
    class_ = image.split('_')[1]
    classes.append(class_)
    paths.append(test_path+'/'+class_+'/'+image)

test_df['classes'] = classes
test_df['path'] = paths

# # path = train_path + 'cat/*.jpeg'
# for file in train_df["images"]:
#     img = cv2.imread(file)
#     img = cv2.resize(img, (30, 30))
#     print(img)
#     break
#     img = img.reshape(img.shape[0]*img.shape[1]*img.shape[2])
#     images.append(img)

In [18]:
train_df

,images,classes,path
0,flickr_cat_000002.jpg,cat,/Kodlar/MachineLearning/Proje2/train/cat/flick...
1,flickr_cat_000003.jpg,cat,/Kodlar/MachineLearning/Proje2/train/cat/flick...
2,flickr_cat_000004.jpg,cat,/Kodlar/MachineLearning/Proje2/train/cat/flick...
3,flickr_cat_000005.jpg,cat,/Kodlar/MachineLearning/Proje2/train/cat/flick...
4,flickr_cat_000006.jpg,cat,/Kodlar/MachineLearning/Proje2/train/cat/flick...
...,...,...,...
14625,pixabay_wild_001249.jpg,wild,/Kodlar/MachineLearning/Proje2/train/wild/pixa...
14626,pixabay_wild_001250.jpg,wild,/Kodlar/MachineLearning/Proje2/train/wild/pixa...
14627,pixabay_wild_001251.jpg,wild,/Kodlar/MachineLearning/Proje2/train/wild/pixa...
14628,pixabay_wild_001252.jpg,wild,/Kodlar/MachineLearning/Proje2/train/wild/pixa...
14629,pixabay_wild_001253.jpg,wild,/Kodlar/MachineLearning/Proje2/train/wild/pixa...

In [5]:
for file in train_df["path"]:
    img = cv2.imread(file)
    img = cv2.resize(img, (30,30))
    img = img.reshape(img.shape[0]*img.shape[1]*img.shape[2])
    images.append(img)
    

images[0]

array([3, 5, 5, ..., 0, 0, 0], dtype=uint8)

In [12]:
type(images)
npList = np.array(images)

In [13]:
type(npList)

numpy.ndarray

In [14]:
data_frame = pd.DataFrame(npList)
data_frame

,0,1,2,3,4,5,6,7,8,9,...,2690,2691,2692,2693,2694,2695,2696,2697,2698,2699
0,3,5,5,3,9,8,0,0,0,0,...,9,0,0,0,1,1,1,0,0,0
1,121,162,195,52,148,202,49,142,198,44,...,61,45,32,33,62,46,47,73,58,56
2,76,182,223,141,137,135,83,180,226,71,...,63,37,32,33,44,39,40,70,64,65
3,216,197,176,96,142,163,85,142,163,79,...,130,152,128,110,76,57,52,70,55,53
4,234,209,183,135,164,176,66,148,179,70,...,183,235,205,180,236,203,177,233,202,177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14625,60,94,94,79,91,97,66,100,115,79,...,216,211,224,250,196,203,230,174,185,213
14626,1,19,6,6,13,8,17,22,20,12,...,40,12,24,36,25,41,54,59,72,86
14627,46,40,21,20,19,9,11,14,5,10,...,86,47,79,47,50,99,61,31,82,44
14628,66,73,82,33,43,53,75,84,93,111,...,187,106,186,189,132,199,198,121,195,183
14629,3,44,62,41,98,119,44,82,116,41,...,221,108,193,246,91,181,235,97,190,245

In [15]:
npList

array([[  3,   5,   5, ...,   0,   0,   0],
       [121, 162, 195, ...,  73,  58,  56],
       [ 76, 182, 223, ...,  70,  64,  65],
       ...,
       [ 46,  40,  21, ...,  31,  82,  44],
       [ 66,  73,  82, ..., 121, 195, 183],
       [  3,  44,  62, ...,  97, 190, 245]], dtype=uint8)

In [ ]:
import numpy as np

class Network:
    def __init__(self, structure):
        self.structure = structure
        self.num_layers = len(structure) 
        self.Bₙ = [np.random.randn(l, 1) for l in structure[1:]] 
        
        self.Wₙ = [np.random.randn(l, next_l) / for l, next_l in zip(structure[:-1], structure[1:])]
        
    def backprop(self, x, y):        
        მJⳆმBₙₛ = [np.zeros(b.shape) for b in self.Bₙ]
        მJⳆმWₙₛ = [np.zeros(W.shape) for W in self.Wₙ]

        Zₙ = [] 
        Aₙ = [] 
        for b, W in zip(self.Bₙ, self.Wₙ):
            z = W.T @ a + b if Zₙ else W.T @ x + b
            a = σ(z)
            Zₙ.append(z)
            Aₙ.append(a)
        
        H = self.num_layers-2
        for L in range(H, -1, -1):
            δ =  σࠤ(Zₙ[L]) * (self.Wₙ[L+1] @ δ) if L != H else ᐁC(Aₙ[L], y) * σࠤ(Zₙ[L])
            მJⳆმBₙₛ[L] = δ
            მJⳆმWₙₛ[L] = Aₙ[L-1] @ δ.T if L != 0 else x @ δ.T
        
        return (მJⳆმBₙₛ, მJⳆმWₙₛ)
    
    def gradient_descent(self, mini_batch, λ):
        #
        მJⳆმBₙ= [np.zeros(b.shape) for b in self.Bₙ]
        მJⳆმWₙ = [np.zeros(W.shape) for W in self.Wₙ]

        for x, y in mini_batch:
            მJⳆმBₙₛ, მJⳆმWₙₛ = self.backprop(x, y)
            მJⳆმBₙ = [მJⳆმb + მJⳆმbₛ for მJⳆმb, მJⳆმbₛ in zip(მJⳆმBₙ, მJⳆმBₙₛ)]  
            მJⳆმWₙ = [მJⳆმW + მJⳆმWₛ for მJⳆმW, მJⳆმWₛ in zip(მJⳆმWₙ, მJⳆმWₙₛ)]

        d = len(mini_batch)
        self.Wₙ = [W - λ/d * მJⳆმW for W, მJⳆმW in zip(self.Wₙ, მJⳆმWₙ)]
        self.Bₙ = [b - λ/d * მJⳆმb for b, მJⳆმb in zip(self.Bₙ, მJⳆმBₙ)]
            
    def train(self, epochs, training_data, λ):
        for j in range(epochs):
            for mini_batch in training_data:
                self.gradient_descent(mini_batch, λ)       
                


def ᐁC(aᴺ, y):    
    return (aᴺ-y)                 #so we can easily change the cost.


def σ(z):
    return 1.0/(1.0+np.exp(-z))


def σࠤ(z):
    return σ(z)*(1-σ(z))


my_net = Network([256, 128 ,3])
print("Initial Weights:")
print(my_net.Wₙ[0])
#the following generates a list of cnt vectors of length dim.
random_vectors = lambda dim, cnt: [np.random.rand(dim, 1) for i in range(cnt)]
random_batch= list(zip(random_vectors(3, 64) , random_vectors(2, 64)))
my_net.gradient_descent(random_batch, 3.0)
print("Optimized Weights:")
print(my_net.Wₙ[0])

In [ ]:
class Network():

    # hidden layer 
    def __init__(self, x, w, y):
        self.x = x 
        self.w = w 
        self.y =